# ะะผั, ะบะพัะพัะพะต ะพััะฐะทะธััั ะฝะฐ ะฟะปะฐััะพัะผะต CTFd
name: "kalik"
# ะะฐั Telegram ะฝะธะบะฝะตะนะผ (ะฝะต ะพัะพะฑัะฐะถะฐะตััั ะฝะฐ ะฟะปะฐััะพัะผะต)
author: "@jim_amlt"
# ะะฐัะตะณะพัะธั - ะฝะฐะทะฒะฐะฝะธะต ะฟะฐะฟะบะธ, ะฒ ะบะพัะพัะพะน ะปะตะถะธั ัะฐัะบ
category: "osint"
# ะะฐัะตะณะพัะธั ะฑัะดะตั ะพัะพะฑัะฐะถะฐัััั ะฝะฐ ะฟะปะฐััะพัะผะต ะฒ ะพะฟะธัะฐะฝะธะธ ัะฐัะบะฐ. ะะพะดะดะตัะถะธะฒะฐะตััั md ัะพัะผะฐั
description: |
  โ๏ธ๐ซ๐โโ๏ธ ะฃัะฐััะน ะฑะฐัั ะธะผะฟะตัโะบะฐะปััะฝ โ ะฟะพะดัะตัะฐะป! ๐คด๐ป๐ข
  ะะพะฒะพััั, ะบะพะณะดะฐ ััะพั ัะตัััะทะฝัะน ัะธะฟ ัััะฐะตั ััะฑะธัั ะบะพัะฐะฑะปะธ ๐ช๐ถ ะธ ะบัััะธัั ัะตัะพัะผั ๐๐ง, ะพะฝ ะปะพะฒะบะพ ัะฝะธะผะฐะตั ะปะฐัะฝัะน ะฝะฐะณััะดะฝะธะบ ๐ก๏ธ, ะดะพััะฐัั ะฟัะทะฐััั ะบะพะปะฑั ๐ซ๐ ะธ ััััะฐะธะฒะฐะตั ัะฐััะบะธะน โะดัะผะพัะผะพััโ ๐ค๐จ๐จ

  ะกะผะพััะธ, ะบะฐะบ ัะฒะตัะตะฝะฝะพ ะดะตัะถะธั ะผัะฝะดัััะบ: ััั ัะตะฑะต ะธ ะฒะพะตะฝะฝะฐั ะฒัะฟัะฐะฒะบะฐ ๐ซกโ๏ธ, ะธ ะพะฟััะฝัะน ะทะฐะฑะธะฒัะธะบ ะฒ ะพะดะฝะพะผ ะปะธัะต๐คบ๐งโ๐๐จ.
  ะฃะณะพะปัะบ ัะฐะทะณะพัะตะปัั ๐ฅ๐ค โ ะธ ะฟะพััะป ะณัััะพะน ะพะฑะปะฐัะพะบ โ๏ธโ๏ธ, ะฑัะดัะพ ัะฐะทะฐะผะธ ัะธะณะฝะฐะปะฐ ะฟะพะดะฐัั ๐ถ:
  ยซะญะน, ะฑะพััะต, ะฝะต ััะตัะธัะตัั, ัะตะนัะฐั ะฑัะดะตั ะผะฐััะพะฒะฐั ะฝะฐะบััะบะฐ ะฑะตะท ะพะฑััะฒะปะตะฝะธั ะฒะพะนะฝั!ยป ๐๐คค๐๏ธ๐ซ

  ะัะบะฐ ะฝะฐ ัะฐััะต โ๐ช โ ัะธัััะน ะฝะฐะผัะบ: ยซะัะฐััั, ะบัะพ ะฟะตัะฒัะน ะบ ัะฐัะต โ ัะพะผั ะฑะพัััะบะธะต ัะธััะปั ๐๐ ะธ ะฑะตะทะปะธะผะธั ะฝะฐ ัะธัะพะฟัะธะบ!ยป ๐ฅค๐ค๓ฆ๓ข๓๓๓ค๓๓ซ๓๓ฉ๓๓๓ฆ๓๓ฉ๓
  ะ ัะฐะผ ัะผะพััะธั ะฒ ััะพัะพะฝั ะณะพัะธะทะพะฝัะฐ ๐๐, ะฑัะดัะพ ะฒัััะธััะฒะฐะตั, ะณะดะต ะตัั ะผะพะถะฝะพ ะพัะฝะพะฒะฐัั ะพัะตัะตะดะฝะพะน โะกะฐะฝโะัะผะฑััะณโ ๐ฐ๐ฌ๐.

  ะะพะดัะธะฝัะฝะฝัะต ะฟะธััั ๐๐๏ธ: ะฟะพัะปะต ะฟะฐัั ะทะฐััะถะตะบ ะพะฝ ัะฟะพัะพะฑะตะฝ ัะฐัะฟะธัะฐัั ะฝะพะฒัะน ัะตะณะปะฐะผะตะฝั ัะปะพัะฐ โ๏ธ๐, ะฟะตัะตะฒะตัะฑะพะฒะฐัั ะฟะฐัั ะธะฝะถะตะฝะตัะพะฒ ๐งโ๐ป๐งโ๐ง ะธ ะฒัั ััะพ โ ะฝะต ะฒัะฟััะบะฐั ะผัะฝะดัััะบ ะธะท ััะบะธ ๐๓ก๓๓๓ฃ๓ข๓ค๓ง๓๓ข๓๓๓ฆ๓๓ฉ๓๓๓ฆ๓๐คฒ.
  ะะฐะฒัะบ: ะฑะตัะฟัะพะฒะพะดะฝะฐั ัะตัะพัะผะฐัะธั ะณะพััะดะฐัััะฒะฐ ัะตัะตะท ะบะฐะปััะฝโะพะฑะปะฐะบะพ๐๐ก๐ญ

  ะขะฐะบ ััะพ ะฑะตัะตะณะธัะตัั โ๏ธ, ะฟะพะบะฐ ะพะฝ ัะฐัะบะฐะปัะตั ัะณะปะธ ๐ฅ๓๓ฉ๓ค๓๓๓๓๓๓๓ค๓ญ โ ะปัะฑะพะน ะฟัะธะบะฐะท ะผะพะถะตั ะฟัะธะปะตัะตัั ั ะดัะผะบะพะผ! โ๏ธ๐๐จ
  ะงะตััั ะพัะดะฐะปะธ ๐โโ๏ธ, ะฒะบััะฝัะบ ะทะฐะฑะธะปะธ ๐๐, ะธ ะฟะพะณะฝะฐะปะธ ัััะพะธัั ัะฒะตัะปะพะต ััะผะฐะฝะฝะพะต ะฑัะดััะตะต ๐ค๐ป๐ซโจ๐
  
  ![ะัััะพะฟัะปะพ I ๐๐จ](https://sun9-21.userapi.com/impg/y4lHXNwczQ-CD12mGucMWqdq2G_O1zXgzjjZ1g/E_t1Xap_59w.jpg?size=1024x1536&quality=95&sign=5aa641d94ba4ea54fe45696811ef806e&type=album)
# ะกััะปะบะฐ ะฝะฐ ะฒะฐั ะขะ ะฐะบะบะฐัะฝั, ััะพะฑั ั ะฒะฐะผะธ ะผะพะณะปะธ ะพะฟะตัะฐัะธะฒะฝะพ ัะฒัะทะฐัััั ะฟะพ ะทะฐะดะฐัะต
attribution: "ะะฒัะพั [@jim_amlt](https://t.me/jim_amlt)"
value: 100
type: dynamic

# Reference - https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
extra:
    initial: 100
    decay: 10
    minimum: 10

# ะะฟะธัะฐะฝะธะต ะบะฐะบ ะบะพะฝะฝะตะบัะธัััั ะบ ะฒะฐัะตะน ะทะฐะดะฐัะต. ะกัะดะฐ ะถะต ะผะพะถะฝะพ ะธ ัััะปะบั ะดะฐัั, ะตัะปะธ ะฝะต ะฒ ะพะฟะธัะฐะฝะธะธ
#connection_info: "nc example.com 5432"

# ะะฐัะบะพะผะผะตะฝัะธััะนัะต, ะตัะปะธ ัะพัะธัะต ัะดะตะปะฐัั ัะฐะบ, ััะพะฑั ั ัะฐัะบะฐ ะฑัะปะพ ะพะณัะฐะฝะธัะตะฝะฝะพะต ัะธัะปะพ ะฟะพะฟััะพะบ ัะดะฐัะธ
# ะั ะฒ ัะฐะผะบะฐั VrnCTF ะฝะต ะธัะฟะพะปัะทัะตะผ
# attempts: 5

# ะัะต ัะฟะพัะพะฑั ะพะฟะธัะฐัั ัะปะฐะณ
# flags:
#     # A static case sensitive flag
#     - flag{3xampl3}
#     # A static case sensitive flag created with a dictionary
#     - {
#         type: "static",
#         content: "flag{wat}",
#     }
#     # A static case insensitive flag
#     - {
#         type: "static",
#         content: "flag{wat}",
#         data: "case_insensitive",
#     }
#     # A regex case insensitive flag
#     - {
#         type: "regex",
#         content: "(.*)STUFF(.*)",
#         data: "case_insensitive",
#     }

flags:
  - vrnctf{dym0v0y_1mp3r470r_dv0yn060_y4bl0chk4}

# ะัะพะฑะพ ะฝะธ ะฝะฐ ััะพ ะฝะต ะฒะปะธัะตั, ะฟะพ ะถะตะปะฐะฝะธั ะผะพะถะฝะพ ัะฐัะบะพะผะผะตะฝัะธัะพะฒะฐัั ะธ ะทะฐะฟะพะปะฝะธัั
# topics:
#     - sql injection

# ะคะฐะนะปั ะธะท ะฟะฐะฟะบะธ public, ะบะพัะพััะต ัะฐะทะดะฐะตะผ ะฟะพะปัะทะพะฒะฐัะตะปัะผ. ะะธะฑะพ ัะตะบััะพะฒัะต ัะฐะนะปะธะบะธ, ะปะธะฑะพ ะฐััะธะฒั
# ะกะธะปัะฝะพ ะถะธัะฝัะต ัะฐะนะปั ัะฐะทะดะฐะตะผ ัะตัะตะท ะณัะณะป-ะพะฑะปะฐะบะพ/ัะฝะดะตะบั-ะดะธัะบ/ะปะธะฝะบ ั s3
files:
#  - public/house.png
#  - public/app.py

# ะฅะธะฝัั ะฟะพ ัะผะพะปัะฐะฝะธั ัะบัััั, ัะดะตะปะฐะนัะต ะธั ะทะฐัะฐะฝะตะต, ะธั ะพัะบัะพะตะผ ะฝะฐ ะฟะพะปะพะฒะธะฝะต ัะพัะตะฒะฝะพะฒะฐะฝะธะน ะฝะฐ ะฝะตัะตัะตะฝะฝัะต ัะฐัะบะธ
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

hints:
#  - ะะฐะบ-ัะพ ัะปะธัะบะพะผ ะผะฝะพะณะพ ัะผะพะดะทะธ
#  - ะั ัะฒะฝะพ ััะพ-ัะพ ะฝะต ัะฐะบ ั ัะผะพะดะทะธ

# ะัะปะธ ะฒะฐั ัะฐัะบ ะทะฐะฒะธัะธั ะพั ะดััะณะพะณะพ ัะฐัะบะฐ, ะฝะฐะฟัะธะผะตั, ะพะฝะธ ะธะดัั ะดััะณ ะทะฐ ะดััะณะพะผ ะธ ะฑะตะท ัะดะฐัะธ ะพะดะฝะพะณะพ ะฝะต ะฑัะดะตั ะดะพัััะฟะตะฝ ะดััะณะพะน
# requirements:
#     - "Warmup"
#     - "Are you alive"

# visible/hidden ะฝะฐ ะฟะปะฐััะพัะผะต
state: visible

# ะะต ััะพะณะฐะตะผ, ะฒะตััะธั ัะฟะตัะธัะธะบะฐัะธะธ
version: "0.1"
